language: csharp
sudo: false
dist: trusty
mono: latest
dotnet: 2.0.0

before_install:
  - nvm install 8.11.1
  - nvm use 8.11.1
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true

script:
  - ./fake.sh build
